### ISSUE TITLE
Facebook Login

### ISSUE THREAD

**Issue by kube** [42Zavattas/generator-bangular#16]
Integrate directly facebook login would be a cool feature (imo).

**Comment by brunowego** [comment]
+1

**Comment by Apercu** [comment]
Sorry for the (very) late response.

We provide a passport main support and an example for the local strategy. I don't think integrate facebook (even as an option) would be a good idea, since we won't be able to refuse to integrate any other strategy for one user specific needs.

What we provide is the root, you only have to make the leaf, and honestly integrate any strategy is pretty straight-forward if you follow correctly their Readme.

If you have any other input @meriadec, feel free to add it

**Comment by meriadec** [comment]
The analogy root/leaf totally blew my mind, and I can only agree with that.
I've heard that **generator-angular-fullstack** integrates facebook auth as an option, maybe it will fit more your needs.. (and you can also have a pre-installed Twitter Bootstrap & jquery :stuck_out_tongue_winking_eye: )
