### ISSUE TITLE
What about bootstrap, there is no way to simply add bootstrap to the generated template

### ISSUE THREAD

**Issue by athakral** [42Zavattas/generator-bangular#34]
I tried adding the bower-component 

https://github.com/twbs/bootstrap-sass#c-bower I can go ahead and modify the task, but I think this is a missing piece .

**Comment by Apercu** [comment]
Hi,

The bootstrap can't be automatically injected because the css is not compiled and thus not referenced in the `bower.json` file (https://github.com/twbs/bootstrap-sass/blob/master/bower.json#L13).
You can try, as described in their docs:

```@import "bootstrap";
```

in your main scss file.
You can also use a CDN (ex: https://www.bootstrapcdn.com/), or use the main bootstrap repo (https://github.com/twbs/bootstrap) and link the `dist/css/bootstrap.min.css` file in your `index.html`.

**Comment by meriadec** [comment]
@athakral does it answer your question?
