### ISSUE TITLE
Gulp preview question.

### ISSUE THREAD

**Issue by jmsherry** [42Zavattas/generator-bangular#35]
Is gulp preview meant to just open a file rather than serve it?

**Comment by Apercu** [comment]
The preview task will build the app, start a server in production mode and open the local url.

**Comment by meriadec** [comment]
Hi, since [this fix](https://github.com/42Zavattas/generator-bangular/commit/ad62d5cd00623c6dc13d61c898046eebe8ea8188) there was a problem with the gulp-open in the preview task (it was opening the index file instead of going to the served url).

It's not yet merged in master. We'll do it soon.
Is it related to your problem?

**Comment by jmsherry** [comment]
Ah! Ok, cool. :)

**Comment by Apercu** [comment]
The [0.11.4](https://github.com/42Zavattas/generator-bangular/releases/tag/0.11.4) version has been landed on npm.

**Comment by meriadec** [comment]
:tada:
