### ISSUE TITLE
gulp test not working on a clean install.

### ISSUE THREAD

**Issue by rudolph2907** [42Zavattas/generator-bangular#39]
Getting the following error on: **gulp test** after doing a clean generate.
        

> Error: [$injector:modulerr] Failed to instantiate module ng due to: TypeError: 'undefined' is not an object (evaluating 'Function.prototype.bind.apply')

**Comment by meriadec** [comment]
I guess it's because [PhantomJs 1.x does not implement Function.prototype.bind](https://github.com/ariya/phantomjs/issues/10522), can you try by putting the [phantomjs-polyfill](https://www.npmjs.com/package/phantomjs-polyfill) into karma conf [here](https://github.com/42Zavattas/generator-bangular/blob/master/app/templates/karma.conf.js(karma)#L35) ? (sry no time to test it now by myself). If it works we should add it into generator.

**Comment by rudolph2907** [comment]
Thanks for the speedy response, meriadec.  I've tried it and it doesn't seem to make an difference.

**Comment by rudolph2907** [comment]
Ok seems to find a fix:
Install the latest phantomjs and then the latest karma-phantomjs-launcher and it seems to work.

**Comment by meriadec** [comment]
Okay, nice :p we will update these deps very soon. Thanks!
