### ISSUE TITLE
Preview doesn't work properly if project name contains hyphen.

### ISSUE THREAD

**Issue by b1r3k** [42Zavattas/generator-bangular#7]
.yo-rc.json
```
{
  "generator-bangular": {
    "version": "0.7.4",
    "filters": {
      "backend": "json",
      "ngCookies": true,
      "ngSanitize": true
    }
  }
}
```

Then I launch preview but weird thing happens. Firstly, basic view is served with app name rather than with controller name. Most important thing is that app starts to do some recursive calls which provokes Firefox to display dialog about stopping script. Chrome just lets tab die. Here is console output:
```
Error: [$injector:nomod] Module 'bangularapp' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument. http://errors.angularjs.org/1.3.13/$injector/nomod?p0=bangularapp
"Error: too much recursion
i/</<@http://localhost:9000/app.b3ec67bb.js:2:20716
o@http://localhost:9000/app.b3ec67bb.js:1:795
i/<@http://localhost:9000/app.b3ec67bb.js:2:20685
rn/this.$get</<@http://localhost:9000/app.b3ec67bb.js:2:7032
oe@http://localhost:9000/app.b3ec67bb.js:2:3749
b@http://localhost:9000/app.b3ec67bb.js:1:29795
s@http://localhost:9000/app.b3ec67bb.js:1:25618
V/<@http://localhost:9000/app.b3ec67bb.js:1:25114
R/r@http://localhost:9000/app.b3ec67bb.js:1:26107
l@http://localhost:9000/app.b3ec67bb.js:1:28288
l@http://localhost:9000/app.b3ec67bb.js:5:7520
i/<.link@http://localhost:9000/app.b3ec67bb.js:5:7755
oe@http://localhost:9000/app.b3ec67bb.js:2:3727
b@http://localhost:9000/app.b3ec67bb.js:1:29795
s@http://localhost:9000/app.b3ec67bb.js:1:25618
V/<@http://localhost:9000/app.b3ec67bb.js:1:25114
o/<.link@http://localhost:9000/app.b3ec67bb.js:5:8076
oe@http://localhost:9000/app.b3ec67bb.js:2:3727
b@http://localhost:9000/app.b3ec67bb.js:1:29795
s@http://localhost:9000/app."[…] "<!-- ngView:  -->"
```
Most likely issue comes from using hyphen in project name. For output I've used bangular-app, while if I use bangular everything works fine.

**Comment by Apercu** [comment]
Hi,

This naming error just have been fixed on the develop branch with the https://github.com/42Zavattas/generator-bangular/commit/b62b8aada25b26b30c8699ff969861f5773b585b[b62b8aa] commit. The 0.7.5 will be launched shortly.

To fix your problem either you have to scaffold another app with the new version or made yourself the changes that introduces this commit. I would recommend the first solution since another [important fix](https://github.com/42Zavattas/generator-bangular/commit/70b6b37a24d868fcbe14ca0dc034d0170024ab68) will appear in 0.7.5.

Feel free to update your status here.

**Comment by b1r3k** [comment]
Looks good to me, thanks!
