### ISSUE TITLE
browsersync

### ISSUE THREAD

**Issue by kaminskypavel** [42Zavattas/generator-bangular#8]
excellent boilerplate! 
can be even better with browsersync..

**Comment by meriadec** [comment]
Hi, thanks for your feedback.

Yes, it could be a good idea as browsersync brings interesting features (such as scroll sync). Also, we have to do some performance / speed tests for definitely adopt it instead of livereload.
This generator is focused on speed, so it's very important for us :rocket: !

**Comment by kaminskypavel** [comment]
perfect. let me know if any help needed with configuring gulp or anything.

**Comment by kaminskypavel** [comment]
Good job! Thanks
